Add syslinux-utils to Recommends + adjust error message for isohybrid
isohybrid was moved from isolinux to syslinux-utils in Debian/jessie,
see #751724

diff --git a/grml2iso b/grml2iso
--- a/grml2iso
+++ b/grml2iso
@@ -37,7 +37,7 @@ else
 fi
 
 if ! which isohybrid >/dev/null 2>&1 ; then
-  echo "Error: isohybrid executable not found (install syslinux/isolinux?)." >&2
+  echo "Error: isohybrid executable not found (install syslinux/isolinux/syslinux-utils?)." >&2
   exit 1
 fi
 # }}}
