Support mkisofs or genisoimage in grml2iso. Updated debian/control

diff --git a/grml2iso b/grml2iso
--- a/grml2iso
+++ b/grml2iso
@@ -23,6 +23,15 @@
   [ -n "$GRML2USB" ] || GRML2USB='grml2usb'
 # work directory for creating the filesystem
   [ -n "$WRKDIR" ]   || WRKDIR='/tmp/grml2iso.tmp'
+# support mkisofs as well as genisoimage
+  if which mkisofs >/dev/null 2>&1; then
+    MKISOFS='mkisofs'
+  elif which genisoimage >/dev/null 2>&1; then
+    MKISOFS='genisoimage'
+  else
+    echo >&2 "Error: neither mkisofs nor genisoimage available - can not create ISO."
+    exit 1
+fi
 # }}}
 
 # helper stuff {{{
@@ -124,7 +133,7 @@ Options:
 # }}}
 
 # generate the CD/DVD ISO {{{
-  mkisofs -V 'grml-multiboot' -l -r -J -no-pad \
+  $MKISOFS -V 'grml-multiboot' -l -r -J -no-pad \
     -no-emul-boot -boot-load-size 4 -boot-info-table \
     -b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat \
     -o "$ISOFILE" .
